checked content of first 10 files: Add-Additional-Users.md, Add-Users…
Twi1ightSparkle/matrix-documentation pull request #6
Opened 2021-06-03 06:33 UTC by rtanglao

Partially fixes #5, namely the first 10 files:

- [x] Add-Additional-Users.md , removed miscellaneous z, rest LGTM
- [x] Add-Users.md - created some minor typos, rest LGTM
- [x] Client-Look-and-Feel.md  - fixed some typos and &#8595;
- [x] Frequently-Asked-Questions.md, fixed some typos
- [x] Client-Look-and-Feel.md, fixed some typos
- [x] EMS-Server-With-Custom-Domain.md; fixed some typos
- [x] Get-Your-Own-EMS-Server.md fixed some typos; Down arrow should be &#8595;
- [x] Reset-User-Password.md   fixed some typos;Down arrow should be &#8595;
- [x] Migrate-From-Self-Hosted-to-EMS.md  fixed some typos;Down arrow should be &#8595;
- [x] Set-up-Cross-Signing.md  fixed some typos; Down arrow should be &#8595;

2021-07-05 05:56 UTC, rtanglao commented
- [x] Add-Additional-Users.md , removed miscellaneous z, rest LGTM
- [x] Add-Users.md - created some minor typos, rest LGTM
- [x] Client-Look-and-Feel.md  - fixed some typos and &#8595;
- [x] Frequently-Asked-Questions.html, fixed some typos
- [x] Client-Look-and-Feel., fixed some typos <--- changed down arrow to `&#8595;` which in unicode is `control shift u 2193 enter`
- [x] EMS-Server-With-Custom-Domain; fixed some typos <-- doesn't document homeserver, just  client
- [x] Get-Your-Own-EMS-Server. fixed some typos; Down arrow should be &#8595;
- [x] Reset-User-Password.md   fixed some typos;Down arrow should be &#8595;
- [x] Migrate-From-Self-Hosted-to-EMS.md  fixed some typos;Down arrow should be &#8595;
- [x] Set-up-Cross-Signing.md  fixed some typos; Down arrow should be &#8595;
- [x] Add-Email-to-Your-Account.md <-- July 4, need to change screenshot from staging
- [x] Add-Free-Slack-Bridge.md <-- July 4, change down arrow to `&#8595;<br />`
- [x] Change-Account-Password.md <-- July 4, change down arrow to `&#8595;<br />`
- [x] Check-Status.md <-- July 4, change down arrow to `&#8595;<br />`
- [x] Contribute.md <--- July 4, change `is` to `are`
- [x] Create-a-Conference-Call-in-a-Room.md <-- July 4, change down arrow to `&#8595;<br />`
- [x] Export-and-Import-E2E-Room-Keys.md
- [x] Import-Database-and-Media-Dump.md <-- July 4 no changes
- [x] Leave-Community-On-Dead-Homeserver.md <-- July 4, no changes
- [x] Reset-Cross-Signing.md <-- July 4, change down arrow to `&#8595;<br />`
- [x] Submit-Debug-Logs.md <-- July 4, change down arrow to `&#8595;<br />`
- [x] Summary.md

2021-07-05 15:21 UTC, Twi1ightSparkle requested changes

2021-07-05 15:21 UTC, Twi1ightSparkle commented on src/Add-Email-to-Your-Account.md
> +1. Go to Element `All settings` &#8595;<br />
Please undo all of these. Double space is a line break in markdown

2021-07-06 07:01 UTC, rtanglao commented on src/Add-Email-to-Your-Account.md
> +1. Go to Element `All settings` &#8595;<br />
done

2021-07-06 10:11 UTC, Twi1ightSparkle requested changes

2021-07-06 10:11 UTC, Twi1ightSparkle commented on src/Frequently-Asked-Questions.md
>  #### How do I add RSS integration to my matrix server?
Capital Matrix

2021-07-06 10:11 UTC, Twi1ightSparkle commented on src/Frequently-Asked-Questions.md
> +The client file needs to contain:
Is "needs to" the correct grammar? 🤔 (idk, but it doesn't sound right to me)

2021-07-06 10:11 UTC, Twi1ightSparkle commented on src/Frequently-Asked-Questions.md
> +The server file needs to contain:
Same as above

2021-07-06 10:11 UTC, Twi1ightSparkle commented on src/Frequently-Asked-Questions.md
> +#### If I in the future I want to migrate from EMS to self-hosted, how?
"If **I** in the future **I** want to" ?

2021-07-06 10:11 UTC, Twi1ightSparkle commented on src/Get-Your-Own-EMS-Server.md
> +1. Click `Your Account`, then `Manage Servers` to get started setting up your EMS server.
Adding periods at the end of a list item is fine. But if you are doing it, please be consistent and change all pages

2021-07-06 10:11 UTC, Twi1ightSparkle commented on src/Get-Your-Own-EMS-Server.md
> +1. When it's done, click `Manage hosts` to configure additional settings and add users.
Should there be a period at the end when there is a related image right below?

2021-07-06 10:11 UTC, Twi1ightSparkle commented on src/Submit-Debug-Logs.md
> +11. Enter a GitHub issue link and a description, make sure `Send logs`, amd `Send crash logs` are checked, then tap the send arrow in the top right
amd --> and

2021-07-06 10:11 UTC, Twi1ightSparkle commented on src/Add-Email-to-Your-Account.md
> +1. Go to Element `All settings` &#8595;<br />
Click "Resolve conversation" when you have resolved a review comment :D

2021-07-09 05:45 UTC, rtanglao commented on src/Add-Email-to-Your-Account.md
> +1. Go to Element `All settings`
fixed

2021-07-09 05:45 UTC, rtanglao commented on src/Add-Users.md
> +1. The username and password for the new user is displayed. You will only be able to see this information once so save it in a password manager or some other secure place for future use.
agreed, fixed

2021-07-09 05:46 UTC, rtanglao commented on src/Client-Look-and-Feel.md
> +1. Looks like this in your web browser:
i think my markdown editor corrupted the formatting. fixed

2021-07-09 05:46 UTC, rtanglao commented on src/Create-a-Conference-Call-in-a-Room.md
> +1. To join the room conference, expand the Jitsi section at the top. Then click Join Conference`
fixed four spaces globally

2021-07-09 05:46 UTC, rtanglao commented on src/Frequently-Asked-Questions.md
>  #### How do I add RSS integration to my matrix server?
fixed

2021-07-09 05:49 UTC, rtanglao commented on src/Frequently-Asked-Questions.md
> +The client file needs to contain:
reverso.net grammar checker  says "needs to" is correct
![image](https://user-images.githubusercontent.com/45195/125029571-ba1d2b00-e03e-11eb-86ed-d79cb01826a3.png)

2021-07-09 05:50 UTC, rtanglao commented on src/Frequently-Asked-Questions.md
> +The server file needs to contain:
same as above :-)

2021-07-09 05:55 UTC, rtanglao commented on src/Frequently-Asked-Questions.md
> +#### If I in the future I want to migrate from EMS to self-hosted, how?
made the wording less awkward

2021-07-09 05:56 UTC, rtanglao commented on src/Submit-Debug-Logs.md
> +11. Enter a GitHub issue link and a description, make sure `Send logs`, amd `Send crash logs` are checked, then tap the send arrow in the top right
fixed

2021-07-09 05:57 UTC, rtanglao commented on src/Get-Your-Own-EMS-Server.md
> +1. Click `Your Account`, then `Manage Servers` to get started setting up your EMS server.
took that period out

2021-07-09 05:58 UTC, rtanglao commented on src/Get-Your-Own-EMS-Server.md
> +1. When it's done, click `Manage hosts` to configure additional settings and add users.
i took the period out

2021-07-09 06:14 UTC, rtanglao commented on src/EMS-Server-With-Custom-Domain.md
> +
fixed, again my markdown editor, typora did this i think?!? anyhow switched to Visual Code and fixed it.

2021-07-09 14:54 UTC, Twi1ightSparkle approved these changes
LGTM. Thank you!

2021-07-09 14:54 UTC, merged